<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class CancelInvoiceResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\CancelInvoice200ApplicationJSON $cancelInvoice200ApplicationJSONObject
     */
	
    public ?CancelInvoice200ApplicationJSON $cancelInvoice200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CancelInvoice401ApplicationJSON $cancelInvoice401ApplicationJSONObject
     */
	
    public ?CancelInvoice401ApplicationJSON $cancelInvoice401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CancelInvoice404ApplicationJSON $cancelInvoice404ApplicationJSONObject
     */
	
    public ?CancelInvoice404ApplicationJSON $cancelInvoice404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CancelInvoice500ApplicationJSON $cancelInvoice500ApplicationJSONObject
     */
	
    public ?CancelInvoice500ApplicationJSON $cancelInvoice500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->cancelInvoice200ApplicationJSONObject = null;
		$this->cancelInvoice401ApplicationJSONObject = null;
		$this->cancelInvoice404ApplicationJSONObject = null;
		$this->cancelInvoice500ApplicationJSONObject = null;
	}
}
