<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class CreateCustomerResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateCustomer201ApplicationJSON $createCustomer201ApplicationJSONObject
     */
	
    public ?CreateCustomer201ApplicationJSON $createCustomer201ApplicationJSONObject = null;
    
    /**
     * Error response for validation
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateCustomer400ApplicationJSON $createCustomer400ApplicationJSONObject
     */
	
    public ?CreateCustomer400ApplicationJSON $createCustomer400ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateCustomer401ApplicationJSON $createCustomer401ApplicationJSONObject
     */
	
    public ?CreateCustomer401ApplicationJSON $createCustomer401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateCustomer403ApplicationJSON $createCustomer403ApplicationJSONObject
     */
	
    public ?CreateCustomer403ApplicationJSON $createCustomer403ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateCustomer500ApplicationJSON $createCustomer500ApplicationJSONObject
     */
	
    public ?CreateCustomer500ApplicationJSON $createCustomer500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createCustomer201ApplicationJSONObject = null;
		$this->createCustomer400ApplicationJSONObject = null;
		$this->createCustomer401ApplicationJSONObject = null;
		$this->createCustomer403ApplicationJSONObject = null;
		$this->createCustomer500ApplicationJSONObject = null;
	}
}
