<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class CreateProductResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateProduct201ApplicationJSON $createProduct201ApplicationJSONObject
     */
	
    public ?CreateProduct201ApplicationJSON $createProduct201ApplicationJSONObject = null;
    
    /**
     * Error response for validation
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateProduct400ApplicationJSON $createProduct400ApplicationJSONObject
     */
	
    public ?CreateProduct400ApplicationJSON $createProduct400ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateProduct401ApplicationJSON $createProduct401ApplicationJSONObject
     */
	
    public ?CreateProduct401ApplicationJSON $createProduct401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateProduct500ApplicationJSON $createProduct500ApplicationJSONObject
     */
	
    public ?CreateProduct500ApplicationJSON $createProduct500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createProduct201ApplicationJSONObject = null;
		$this->createProduct400ApplicationJSONObject = null;
		$this->createProduct401ApplicationJSONObject = null;
		$this->createProduct500ApplicationJSONObject = null;
	}
}
