<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class CreateTransactionResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Created
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateTransaction201ApplicationJSON $createTransaction201ApplicationJSONObject
     */
	
    public ?CreateTransaction201ApplicationJSON $createTransaction201ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateTransaction401ApplicationJSON $createTransaction401ApplicationJSONObject
     */
	
    public ?CreateTransaction401ApplicationJSON $createTransaction401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\CreateTransaction500ApplicationJSON $createTransaction500ApplicationJSONObject
     */
	
    public ?CreateTransaction500ApplicationJSON $createTransaction500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->createTransaction201ApplicationJSONObject = null;
		$this->createTransaction401ApplicationJSONObject = null;
		$this->createTransaction500ApplicationJSONObject = null;
	}
}
