<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class DeleteOrderRequest
{
    /**
     * The ID of the order to delete.
     * 
     * @var int $orderID
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=orderID')]
    public int $orderID;
    
	public function __construct()
	{
		$this->orderID = 0;
	}
}
