<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetCustomerResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetCustomer200ApplicationJSON $getCustomer200ApplicationJSONObject
     */
	
    public ?GetCustomer200ApplicationJSON $getCustomer200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetCustomer401ApplicationJSON $getCustomer401ApplicationJSONObject
     */
	
    public ?GetCustomer401ApplicationJSON $getCustomer401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetCustomer403ApplicationJSON $getCustomer403ApplicationJSONObject
     */
	
    public ?GetCustomer403ApplicationJSON $getCustomer403ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetCustomer404ApplicationJSON $getCustomer404ApplicationJSONObject
     */
	
    public ?GetCustomer404ApplicationJSON $getCustomer404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetCustomer500ApplicationJSON $getCustomer500ApplicationJSONObject
     */
	
    public ?GetCustomer500ApplicationJSON $getCustomer500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getCustomer200ApplicationJSONObject = null;
		$this->getCustomer401ApplicationJSONObject = null;
		$this->getCustomer403ApplicationJSONObject = null;
		$this->getCustomer404ApplicationJSONObject = null;
		$this->getCustomer500ApplicationJSONObject = null;
	}
}
