<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetIpAddresses200ApplicationJSONData
{
    /**
     * List of Paddle IPv4 CIDRs.
     * 
     * @var ?array<string> $ipv4Cidrs
     */
	#[\JMS\Serializer\Annotation\SerializedName('ipv4_cidrs')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $ipv4Cidrs = null;
    
	public function __construct()
	{
		$this->ipv4Cidrs = null;
	}
}
