<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetNotificationSettingResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotificationSetting200ApplicationJSON $getNotificationSetting200ApplicationJSONObject
     */
	
    public ?GetNotificationSetting200ApplicationJSON $getNotificationSetting200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotificationSetting401ApplicationJSON $getNotificationSetting401ApplicationJSONObject
     */
	
    public ?GetNotificationSetting401ApplicationJSON $getNotificationSetting401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotificationSetting404ApplicationJSON $getNotificationSetting404ApplicationJSONObject
     */
	
    public ?GetNotificationSetting404ApplicationJSON $getNotificationSetting404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotificationSetting500ApplicationJSON $getNotificationSetting500ApplicationJSONObject
     */
	
    public ?GetNotificationSetting500ApplicationJSON $getNotificationSetting500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getNotificationSetting200ApplicationJSONObject = null;
		$this->getNotificationSetting401ApplicationJSONObject = null;
		$this->getNotificationSetting404ApplicationJSONObject = null;
		$this->getNotificationSetting500ApplicationJSONObject = null;
	}
}
