<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetNotificationResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotification200ApplicationJSON $getNotification200ApplicationJSONObject
     */
	
    public ?GetNotification200ApplicationJSON $getNotification200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotification401ApplicationJSON $getNotification401ApplicationJSONObject
     */
	
    public ?GetNotification401ApplicationJSON $getNotification401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotification404ApplicationJSON $getNotification404ApplicationJSONObject
     */
	
    public ?GetNotification404ApplicationJSON $getNotification404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetNotification500ApplicationJSON $getNotification500ApplicationJSONObject
     */
	
    public ?GetNotification500ApplicationJSON $getNotification500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getNotification200ApplicationJSONObject = null;
		$this->getNotification401ApplicationJSONObject = null;
		$this->getNotification404ApplicationJSONObject = null;
		$this->getNotification500ApplicationJSONObject = null;
	}
}
