<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class GetPriceRequest
{
    /**
     * Include related entities in the response.
     * 
     * @var ?\paddle\Paddle\Models\Shared\IncludePrice $include
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include')]
    public ?\paddle\Paddle\Models\Shared\IncludePrice $include = null;
    
    /**
     * Paddle ID of the price entity to work with.
     * 
     * @var string $priceId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=price_id')]
    public string $priceId;
    
	public function __construct()
	{
		$this->include = null;
		$this->priceId = "";
	}
}
