<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetPriceResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetPrice200ApplicationJSON $getPrice200ApplicationJSONObject
     */
	
    public ?GetPrice200ApplicationJSON $getPrice200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetPrice401ApplicationJSON $getPrice401ApplicationJSONObject
     */
	
    public ?GetPrice401ApplicationJSON $getPrice401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetPrice404ApplicationJSON $getPrice404ApplicationJSONObject
     */
	
    public ?GetPrice404ApplicationJSON $getPrice404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetPrice500ApplicationJSON $getPrice500ApplicationJSONObject
     */
	
    public ?GetPrice500ApplicationJSON $getPrice500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getPrice200ApplicationJSONObject = null;
		$this->getPrice401ApplicationJSONObject = null;
		$this->getPrice404ApplicationJSONObject = null;
		$this->getPrice500ApplicationJSONObject = null;
	}
}
