<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetSubscriptionResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetSubscription200ApplicationJSON $getSubscription200ApplicationJSONObject
     */
	
    public ?GetSubscription200ApplicationJSON $getSubscription200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetSubscription401ApplicationJSON $getSubscription401ApplicationJSONObject
     */
	
    public ?GetSubscription401ApplicationJSON $getSubscription401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetSubscription404ApplicationJSON $getSubscription404ApplicationJSONObject
     */
	
    public ?GetSubscription404ApplicationJSON $getSubscription404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetSubscription500ApplicationJSON $getSubscription500ApplicationJSONObject
     */
	
    public ?GetSubscription500ApplicationJSON $getSubscription500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getSubscription200ApplicationJSONObject = null;
		$this->getSubscription401ApplicationJSONObject = null;
		$this->getSubscription404ApplicationJSONObject = null;
		$this->getSubscription500ApplicationJSONObject = null;
	}
}
