<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


/**
 * GetSubscriptionUpdatePaymentMethodTransaction200ApplicationJSONOutput - OK
 * 
 * @package paddle\Paddle\Models\Operations
 * @access public
 */
class GetSubscriptionUpdatePaymentMethodTransaction200ApplicationJSONOutput
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Operations\GetSubscriptionUpdatePaymentMethodTransaction200ApplicationJSONTransactionOutput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetSubscriptionUpdatePaymentMethodTransaction200ApplicationJSONTransactionOutput $data = null;
    
	public function __construct()
	{
		$this->data = null;
	}
}
