<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class GetTransactionInvoiceResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetTransactionInvoice200ApplicationJSON $getTransactionInvoice200ApplicationJSONObject
     */
	
    public ?GetTransactionInvoice200ApplicationJSON $getTransactionInvoice200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetTransactionInvoice401ApplicationJSON $getTransactionInvoice401ApplicationJSONObject
     */
	
    public ?GetTransactionInvoice401ApplicationJSON $getTransactionInvoice401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetTransactionInvoice404ApplicationJSON $getTransactionInvoice404ApplicationJSONObject
     */
	
    public ?GetTransactionInvoice404ApplicationJSON $getTransactionInvoice404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\GetTransactionInvoice500ApplicationJSON $getTransactionInvoice500ApplicationJSONObject
     */
	
    public ?GetTransactionInvoice500ApplicationJSON $getTransactionInvoice500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->getTransactionInvoice200ApplicationJSONObject = null;
		$this->getTransactionInvoice401ApplicationJSONObject = null;
		$this->getTransactionInvoice404ApplicationJSONObject = null;
		$this->getTransactionInvoice500ApplicationJSONObject = null;
	}
}
