<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ListAddressesResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListAddresses200ApplicationJSON $listAddresses200ApplicationJSONObject
     */
	
    public ?ListAddresses200ApplicationJSON $listAddresses200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListAddresses401ApplicationJSON $listAddresses401ApplicationJSONObject
     */
	
    public ?ListAddresses401ApplicationJSON $listAddresses401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListAddresses403ApplicationJSON $listAddresses403ApplicationJSONObject
     */
	
    public ?ListAddresses403ApplicationJSON $listAddresses403ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListAddresses404ApplicationJSON $listAddresses404ApplicationJSONObject
     */
	
    public ?ListAddresses404ApplicationJSON $listAddresses404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListAddresses500ApplicationJSON $listAddresses500ApplicationJSONObject
     */
	
    public ?ListAddresses500ApplicationJSON $listAddresses500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listAddresses200ApplicationJSONObject = null;
		$this->listAddresses401ApplicationJSONObject = null;
		$this->listAddresses403ApplicationJSONObject = null;
		$this->listAddresses404ApplicationJSONObject = null;
		$this->listAddresses500ApplicationJSONObject = null;
	}
}
