<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ListInvoicesResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListInvoices200ApplicationJSON $listInvoices200ApplicationJSONObject
     */
	
    public ?ListInvoices200ApplicationJSON $listInvoices200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListInvoices401ApplicationJSON $listInvoices401ApplicationJSONObject
     */
	
    public ?ListInvoices401ApplicationJSON $listInvoices401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListInvoices500ApplicationJSON $listInvoices500ApplicationJSONObject
     */
	
    public ?ListInvoices500ApplicationJSON $listInvoices500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listInvoices200ApplicationJSONObject = null;
		$this->listInvoices401ApplicationJSONObject = null;
		$this->listInvoices500ApplicationJSONObject = null;
	}
}
