<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class ListNotificationLogsRequest
{
    /**
     * Return entities after the specified cursor. Used for working through paginated results.
     * 
     * @var ?string $after
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=after')]
    public ?string $after = null;
    
    /**
     * Paddle ID of the notification entity to work with.
     * 
     * @var string $notificationId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=notification_id')]
    public string $notificationId;
    
    /**
     * Set how many entities are returned per page.
     * 
     * @var ?int $perPage
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=per_page')]
    public ?int $perPage = null;
    
	public function __construct()
	{
		$this->after = null;
		$this->notificationId = "";
		$this->perPage = null;
	}
}
