<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ListCreditBalancesResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListCreditBalances200ApplicationJSON $listCreditBalances200ApplicationJSONObject
     */
	
    public ?ListCreditBalances200ApplicationJSON $listCreditBalances200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListCreditBalances400ApplicationJSON $listCreditBalances400ApplicationJSONObject
     */
	
    public ?ListCreditBalances400ApplicationJSON $listCreditBalances400ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListCreditBalances404ApplicationJSON $listCreditBalances404ApplicationJSONObject
     */
	
    public ?ListCreditBalances404ApplicationJSON $listCreditBalances404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListCreditBalances500ApplicationJSON $listCreditBalances500ApplicationJSONObject
     */
	
    public ?ListCreditBalances500ApplicationJSON $listCreditBalances500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listCreditBalances200ApplicationJSONObject = null;
		$this->listCreditBalances400ApplicationJSONObject = null;
		$this->listCreditBalances404ApplicationJSONObject = null;
		$this->listCreditBalances500ApplicationJSONObject = null;
	}
}
