<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ListSubscriptionsResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListSubscriptions200ApplicationJSON $listSubscriptions200ApplicationJSONObject
     */
	
    public ?ListSubscriptions200ApplicationJSON $listSubscriptions200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListSubscriptions401ApplicationJSON $listSubscriptions401ApplicationJSONObject
     */
	
    public ?ListSubscriptions401ApplicationJSON $listSubscriptions401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ListSubscriptions500ApplicationJSON $listSubscriptions500ApplicationJSONObject
     */
	
    public ?ListSubscriptions500ApplicationJSON $listSubscriptions500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->listSubscriptions200ApplicationJSONObject = null;
		$this->listSubscriptions401ApplicationJSONObject = null;
		$this->listSubscriptions500ApplicationJSONObject = null;
	}
}
