<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class PauseSubscriptionRequestBody
{
    /**
     * When this scheduled change should take effect from. `immediately` is only allowed when canceling or resuming a paused subscription.
     * 
     * @var ?\paddle\Paddle\Models\Shared\EffectiveFromNullable $effectiveFrom
     */
	#[\JMS\Serializer\Annotation\SerializedName('effective_from')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\EffectiveFromNullable>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\paddle\Paddle\Models\Shared\EffectiveFromNullable $effectiveFrom = null;
    
    /**
     * Timestamp following the RFC 3339 standard
     * 
     * @var ?\DateTime $resumeAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('resume_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $resumeAt = null;
    
	public function __construct()
	{
		$this->effectiveFrom = null;
		$this->resumeAt = null;
	}
}
