<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class PostNotificationSettingsNotificationSettingIdReplayResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PostNotificationSettingsNotificationSettingIdReplay401ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay401ApplicationJSONObject
     */
	
    public ?PostNotificationSettingsNotificationSettingIdReplay401ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PostNotificationSettingsNotificationSettingIdReplay404ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay404ApplicationJSONObject
     */
	
    public ?PostNotificationSettingsNotificationSettingIdReplay404ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PostNotificationSettingsNotificationSettingIdReplay500ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay500ApplicationJSONObject
     */
	
    public ?PostNotificationSettingsNotificationSettingIdReplay500ApplicationJSON $postNotificationSettingsNotificationSettingIdReplay500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->postNotificationSettingsNotificationSettingIdReplay401ApplicationJSONObject = null;
		$this->postNotificationSettingsNotificationSettingIdReplay404ApplicationJSONObject = null;
		$this->postNotificationSettingsNotificationSettingIdReplay500ApplicationJSONObject = null;
	}
}
