<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class PreviewTransactionResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\PreviewTransaction200ApplicationJSON $previewTransaction200ApplicationJSONObject
     */
	
    public ?PreviewTransaction200ApplicationJSON $previewTransaction200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PreviewTransaction401ApplicationJSON $previewTransaction401ApplicationJSONObject
     */
	
    public ?PreviewTransaction401ApplicationJSON $previewTransaction401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PreviewTransaction500ApplicationJSON $previewTransaction500ApplicationJSONObject
     */
	
    public ?PreviewTransaction500ApplicationJSON $previewTransaction500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->previewTransaction200ApplicationJSONObject = null;
		$this->previewTransaction401ApplicationJSONObject = null;
		$this->previewTransaction500ApplicationJSONObject = null;
	}
}
