<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class PricePreviewResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\PricePreview200ApplicationJSONOutput $pricePreview200ApplicationJSONObject
     */
	
    public ?PricePreview200ApplicationJSONOutput $pricePreview200ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PricePreview401ApplicationJSON $pricePreview401ApplicationJSONObject
     */
	
    public ?PricePreview401ApplicationJSON $pricePreview401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\PricePreview500ApplicationJSON $pricePreview500ApplicationJSONObject
     */
	
    public ?PricePreview500ApplicationJSON $pricePreview500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->pricePreview200ApplicationJSONObject = null;
		$this->pricePreview401ApplicationJSONObject = null;
		$this->pricePreview500ApplicationJSONObject = null;
	}
}
