<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ReplayNotificationResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * Accepted
     * 
     * @var ?\paddle\Paddle\Models\Operations\ReplayNotification202ApplicationJSON $replayNotification202ApplicationJSONObject
     */
	
    public ?ReplayNotification202ApplicationJSON $replayNotification202ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ReplayNotification401ApplicationJSON $replayNotification401ApplicationJSONObject
     */
	
    public ?ReplayNotification401ApplicationJSON $replayNotification401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ReplayNotification404ApplicationJSON $replayNotification404ApplicationJSONObject
     */
	
    public ?ReplayNotification404ApplicationJSON $replayNotification404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\ReplayNotification500ApplicationJSON $replayNotification500ApplicationJSONObject
     */
	
    public ?ReplayNotification500ApplicationJSON $replayNotification500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->replayNotification202ApplicationJSONObject = null;
		$this->replayNotification401ApplicationJSONObject = null;
		$this->replayNotification404ApplicationJSONObject = null;
		$this->replayNotification500ApplicationJSONObject = null;
	}
}
