<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


/**
 * ReplayNotification202ApplicationJSON - Accepted
 * 
 * @package paddle\Paddle\Models\Operations
 * @access public
 */
class ReplayNotification202ApplicationJSON
{
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Operations\ReplayNotification202ApplicationJSONData')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ReplayNotification202ApplicationJSONData $data = null;
    
    /**
     * Information about this response.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Meta $meta
     */
	#[\JMS\Serializer\Annotation\SerializedName('meta')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Meta')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\paddle\Paddle\Models\Shared\Meta $meta = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->meta = null;
	}
}
