<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class ResumeSubscriptionRequestBodyEffectiveFromDate
{
    /**
     * RFC 3339 datetime string.
     * 
     * @var \DateTime $effectiveFrom
     */
	#[\JMS\Serializer\Annotation\SerializedName('effective_from')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $effectiveFrom;
    
	public function __construct()
	{
		$this->effectiveFrom = new \DateTime();
	}
}
