<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class UpdateProductResponse
{
    /**
     * HTTP response content type for this operation
     * 
     * @var string $contentType
     */
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * HTTP response status code for this operation
     * 
     * @var int $statusCode
     */
	
    public int $statusCode;
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     * 
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateProduct200ApplicationJSON $updateProduct200ApplicationJSONObject
     */
	
    public ?UpdateProduct200ApplicationJSON $updateProduct200ApplicationJSONObject = null;
    
    /**
     * Error response for validation
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateProduct400ApplicationJSON $updateProduct400ApplicationJSONObject
     */
	
    public ?UpdateProduct400ApplicationJSON $updateProduct400ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateProduct401ApplicationJSON $updateProduct401ApplicationJSONObject
     */
	
    public ?UpdateProduct401ApplicationJSON $updateProduct401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateProduct404ApplicationJSON $updateProduct404ApplicationJSONObject
     */
	
    public ?UpdateProduct404ApplicationJSON $updateProduct404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateProduct500ApplicationJSON $updateProduct500ApplicationJSONObject
     */
	
    public ?UpdateProduct500ApplicationJSON $updateProduct500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateProduct200ApplicationJSONObject = null;
		$this->updateProduct400ApplicationJSONObject = null;
		$this->updateProduct401ApplicationJSONObject = null;
		$this->updateProduct404ApplicationJSONObject = null;
		$this->updateProduct500ApplicationJSONObject = null;
	}
}
