<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class UpdateBusinessRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\paddle\Paddle\Models\Shared\BusinessInput $businessInput = null;
    
    /**
     * Paddle ID of the business entity to work with.
     * 
     * @var string $businessId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=business_id')]
    public string $businessId;
    
    /**
     * Paddle ID of the customer entity to work with.
     * 
     * @var string $customerId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customer_id')]
    public string $customerId;
    
	public function __construct()
	{
		$this->businessInput = null;
		$this->businessId = "";
		$this->customerId = "";
	}
}
