<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class UpdateInvoiceRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\paddle\Paddle\Models\Shared\InvoiceForPatch $invoiceForPatch = null;
    
    /**
     * Paddle ID of the invoice entity to work with.
     * 
     * @var string $invoiceId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=invoice_id')]
    public string $invoiceId;
    
	public function __construct()
	{
		$this->invoiceForPatch = null;
		$this->invoiceId = "";
	}
}
