<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class UpdateNotificationSettingResponse
{
	
    public string $contentType;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateNotificationSetting200ApplicationJSON $updateNotificationSetting200ApplicationJSONObject
     */
	
    public ?UpdateNotificationSetting200ApplicationJSON $updateNotificationSetting200ApplicationJSONObject = null;
    
    /**
     * Error response for validation
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateNotificationSetting400ApplicationJSON $updateNotificationSetting400ApplicationJSONObject
     */
	
    public ?UpdateNotificationSetting400ApplicationJSON $updateNotificationSetting400ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateNotificationSetting401ApplicationJSON $updateNotificationSetting401ApplicationJSONObject
     */
	
    public ?UpdateNotificationSetting401ApplicationJSON $updateNotificationSetting401ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateNotificationSetting404ApplicationJSON $updateNotificationSetting404ApplicationJSONObject
     */
	
    public ?UpdateNotificationSetting404ApplicationJSON $updateNotificationSetting404ApplicationJSONObject = null;
    
    /**
     * General error response
     * 
     * @var ?\paddle\Paddle\Models\Operations\UpdateNotificationSetting500ApplicationJSON $updateNotificationSetting500ApplicationJSONObject
     */
	
    public ?UpdateNotificationSetting500ApplicationJSON $updateNotificationSetting500ApplicationJSONObject = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->headers = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
		$this->updateNotificationSetting200ApplicationJSONObject = null;
		$this->updateNotificationSetting400ApplicationJSONObject = null;
		$this->updateNotificationSetting401ApplicationJSONObject = null;
		$this->updateNotificationSetting404ApplicationJSONObject = null;
		$this->updateNotificationSetting500ApplicationJSONObject = null;
	}
}
