<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class UpdatePriceRequest
{
    /**
     * $requestBody
     * 
     * @var ?array<string, mixed> $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?array $requestBody = null;
    
    /**
     * Paddle ID of the price entity to work with.
     * 
     * @var string $priceId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=price_id')]
    public string $priceId;
    
	public function __construct()
	{
		$this->requestBody = null;
		$this->priceId = "";
	}
}
