<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class UpdateProductRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\paddle\Paddle\Models\Shared\ProductPatch $productPatch = null;
    
    /**
     * Paddle ID of the product entity to work with.
     * 
     * @var string $productId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=product_id')]
    public string $productId;
    
	public function __construct()
	{
		$this->productPatch = null;
		$this->productId = "";
	}
}
