<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;

use \paddle\Paddle\Utils\SpeakeasyMetadata;
class UpdateDiscountRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?\paddle\Paddle\Models\Shared\DiscountInput $discount = null;
    
    /**
     * Paddle ID of the discount entity to work with.
     * 
     * @var string $discountId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=discount_id')]
    public string $discountId;
    
	public function __construct()
	{
		$this->discount = null;
		$this->discountId = "";
	}
}
