<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Operations;


class UpsertOrderResponse
{
	
    public string $contentType;
    
    /**
     * OK
     * 
     * @var ?\paddle\Paddle\Models\Shared\Order $order
     */
	
    public ?\paddle\Paddle\Models\Shared\Order $order = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->order = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
