<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


enum Action: string
{
    case Chargeback = 'chargeback';
    case ChargebackReverse = 'chargeback_reverse';
    case ChargebackWarning = 'chargeback_warning';
    case Credit = 'credit';
    case CreditReverse = 'credit_reverse';
    case Refund = 'refund';
}
