<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * AdjustmentPayoutTotals - Breakdown of how this adjustment affects your payout balance.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class AdjustmentPayoutTotals
{
    /**
     * Chargeback fees incurred for this adjustment. Only returned when the adjustment `action` is `chargeback` or `chargeback_warning`.
     * 
     * @var ?\paddle\Paddle\Models\Shared\AdjustmentPayoutTotalsChargebackFee $chargebackFee
     */
	#[\JMS\Serializer\Annotation\SerializedName('chargeback_fee')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\AdjustmentPayoutTotalsChargebackFee')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AdjustmentPayoutTotalsChargebackFee $chargebackFee = null;
    
    /**
     * Supported three-letter ISO 4217 currency code for payouts from Paddle.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CurrencyCodePayouts $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCodePayouts>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CurrencyCodePayouts $currencyCode = null;
    
    /**
     * Adjusted payout earnings. This is the adjustment total plus adjusted Paddle fees, minus chargeback fees.
     * 
     * @var ?string $earnings
     */
	#[\JMS\Serializer\Annotation\SerializedName('earnings')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $earnings = null;
    
    /**
     * Adjusted Paddle fee.
     * 
     * @var ?string $fee
     */
	#[\JMS\Serializer\Annotation\SerializedName('fee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fee = null;
    
    /**
     * Adjustment total before tax and fees.
     * 
     * @var ?string $subtotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('subtotal')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subtotal = null;
    
    /**
     * Total tax on the adjustment subtotal.
     * 
     * @var ?string $tax
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tax = null;
    
    /**
     * Adjustment total after tax.
     * 
     * @var ?string $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $total = null;
    
	public function __construct()
	{
		$this->chargebackFee = null;
		$this->currencyCode = null;
		$this->earnings = null;
		$this->fee = null;
		$this->subtotal = null;
		$this->tax = null;
		$this->total = null;
	}
}
