<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * AdjustmentPayoutTotalsChargebackFeeOriginal - Chargeback fee before conversion to the payout currency. `null` when the chargeback fee is the same as the payout currency.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class AdjustmentPayoutTotalsChargebackFeeOriginal
{
    /**
     * Fee amount for this chargeback in the original currency.
     * 
     * @var ?string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $amount = null;
    
    /**
     * Three-letter ISO 4217 currency code for chargeback fees.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CurrencyCodeChargeback $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCodeChargeback>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CurrencyCodeChargeback $currencyCode = null;
    
	public function __construct()
	{
		$this->amount = null;
		$this->currencyCode = null;
	}
}
