<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * AdjustmentPayoutTotalsChargebackFee - Chargeback fees incurred for this adjustment. Only returned when the adjustment `action` is `chargeback` or `chargeback_warning`.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class AdjustmentPayoutTotalsChargebackFee
{
    /**
     * Chargeback fee converted into the payout currency.
     * 
     * @var ?string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $amount = null;
    
    /**
     * Chargeback fee before conversion to the payout currency. `null` when the chargeback fee is the same as the payout currency.
     * 
     * @var ?\paddle\Paddle\Models\Shared\AdjustmentPayoutTotalsChargebackFeeOriginal $original
     */
	#[\JMS\Serializer\Annotation\SerializedName('original')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\AdjustmentPayoutTotalsChargebackFeeOriginal')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?AdjustmentPayoutTotalsChargebackFeeOriginal $original = null;
    
	public function __construct()
	{
		$this->amount = null;
		$this->original = null;
	}
}
