<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * BillingDetails1 - Details for invoicing. Required if `collection_mode` is set to `manual`. Otherwise must be `null`.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class BillingDetails1
{
    /**
     * purchase order number, max 1500 chars
     * 
     * @var ?string $additionalInformation
     */
	#[\JMS\Serializer\Annotation\SerializedName('additional_information')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $additionalInformation = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('enable_checkout')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enableCheckout = null;
    
    /**
     * Setting for the period of time between when the transaction is billed and when it is due. Mandatory when `collection_mode` is set to `manual`.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Period1 $paymentTerms
     */
	#[\JMS\Serializer\Annotation\SerializedName('payment_terms')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Period1')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Period1 $paymentTerms = null;
    
    /**
     * purchase order number, max 100 chars
     * 
     * @var ?string $purchaseOrderNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('purchase_order_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $purchaseOrderNumber = null;
    
	public function __construct()
	{
		$this->additionalInformation = null;
		$this->enableCheckout = null;
		$this->paymentTerms = null;
		$this->purchaseOrderNumber = null;
	}
}
