<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * CreateOrderInput - An input object to creating an order
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class CreateOrderInput
{
    /**
     * Product description of the coffee.
     * 
     * @var ?string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * URI for an image of the coffee.
     * 
     * @var string $image
     */
	#[\JMS\Serializer\Annotation\SerializedName('image')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $image;
    
    /**
     * Product name of the coffee.
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * Suggested cost of the coffee.
     * 
     * @var float $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $price;
    
    /**
     * Fun tagline for the coffee.
     * 
     * @var string $teaser
     */
	#[\JMS\Serializer\Annotation\SerializedName('teaser')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $teaser;
    
	public function __construct()
	{
		$this->description = null;
		$this->image = "";
		$this->name = "";
		$this->price = 0;
		$this->teaser = "";
	}
}
