<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/** Three-letter ISO 4217 currency code for chargeback fees. */
enum CurrencyCodeChargeback: string
{
    case Eur = 'EUR';
    case Gbp = 'GBP';
    case Usd = 'USD';
}
