<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * Data - New or changed entity.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class Data
{
	public function __construct()
	{
	}
}
