<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class Error
{
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $code;
    
	#[\JMS\Serializer\Annotation\SerializedName('detail')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $detail;
    
	#[\JMS\Serializer\Annotation\SerializedName('documentation_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $documentationUrl;
    
    /**
     * $errors
     * 
     * @var ?array<\paddle\Paddle\Models\Shared\Errors> $errors
     */
	#[\JMS\Serializer\Annotation\SerializedName('errors')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\Errors>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $errors = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('extra')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Extra')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Extra $extra = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	public function __construct()
	{
		$this->code = "";
		$this->detail = "";
		$this->documentationUrl = "";
		$this->errors = null;
		$this->extra = null;
		$this->type = "";
	}
}
