<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * EventType - Represents an event type.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class EventType
{
    /**
     * List of API versions that this event type supports.
     * 
     * @var ?array<int> $availableVersions
     */
	#[\JMS\Serializer\Annotation\SerializedName('available_versions')]
    #[\JMS\Serializer\Annotation\Type('array<int>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $availableVersions = null;
    
    /**
     * Short description of this event type.
     * 
     * @var ?string $description
     */
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $description = null;
    
    /**
     * Group for this event type. Typically the entity that this event relates to.
     * 
     * @var ?string $group
     */
	#[\JMS\Serializer\Annotation\SerializedName('group')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $group = null;
    
    /**
     * Type of event sent by Paddle, in the format `entity.event_type`.
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
	public function __construct()
	{
		$this->availableVersions = null;
		$this->description = null;
		$this->group = null;
		$this->name = null;
	}
}
