<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class InvoiceInput
{
	#[\JMS\Serializer\Annotation\SerializedName('address_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $addressId;
    
    /**
     * Details for invoicing. Required if `collection_mode` is set to `manual`. Otherwise must be `null`.
     * 
     * @var \paddle\Paddle\Models\Shared\BillingDetails1 $billingDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('billing_details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\BillingDetails1')]
    public BillingDetails1 $billingDetails;
    
	#[\JMS\Serializer\Annotation\SerializedName('billing_period')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\BillingPeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BillingPeriod $billingPeriod = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('business_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessId = null;
    
    /**
     * Currency codes accepted for invoice. Current accepted currencies for invoice: EUR, GPB and USD.
     * 
     * @var \paddle\Paddle\Models\Shared\CurrencyCodeInvoice $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCodeInvoice>')]
    public CurrencyCodeInvoice $currencyCode;
    
    /**
     * Key/value pairs of any custom data
     * 
     * @var \paddle\Paddle\Models\Shared\CustomDataInvoice $customData
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_data')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\CustomDataInvoice')]
    public CustomDataInvoice $customData;
    
	#[\JMS\Serializer\Annotation\SerializedName('customer_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $customerId;
    
	#[\JMS\Serializer\Annotation\SerializedName('details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\InvoiceDetailsInput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?InvoiceDetailsInput $details = null;
    
    /**
     * $items
     * 
     * @var array<\paddle\Paddle\Models\Shared\InvoiceItem> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\InvoiceItem>')]
    public array $items;
    
	public function __construct()
	{
		$this->addressId = "";
		$this->billingDetails = new \paddle\Paddle\Models\Shared\BillingDetails1();
		$this->billingPeriod = null;
		$this->businessId = null;
		$this->currencyCode = \paddle\Paddle\Models\Shared\CurrencyCodeInvoice::Eur;
		$this->customData = new \paddle\Paddle\Models\Shared\CustomDataInvoice();
		$this->customerId = "";
		$this->details = null;
		$this->items = [];
	}
}
