<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class InvoiceForPatch
{
	#[\JMS\Serializer\Annotation\SerializedName('address_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $addressId = null;
    
    /**
     * Details for invoicing. Required if `collection_mode` is set to `manual`. Otherwise must be `null`.
     * 
     * @var ?\paddle\Paddle\Models\Shared\BillingDetails1 $billingDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('billing_details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\BillingDetails1')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BillingDetails1 $billingDetails = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('billing_period')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\InvoiceForPatchBillingPeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?InvoiceForPatchBillingPeriod $billingPeriod = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('business_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessId = null;
    
    /**
     * Currency codes accepted for invoice. Current accepted currencies for invoice: EUR, GPB and USD.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CurrencyCodeInvoice $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCodeInvoice>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CurrencyCodeInvoice $currencyCode = null;
    
    /**
     * Key/value pairs of any custom data
     * 
     * @var ?\paddle\Paddle\Models\Shared\CustomDataInvoice $customData
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_data')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\CustomDataInvoice')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CustomDataInvoice $customData = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('customer_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerId = null;
    
    /**
     * $items
     * 
     * @var ?array<\paddle\Paddle\Models\Shared\InvoiceItem> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\InvoiceItem>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $items = null;
    
	public function __construct()
	{
		$this->addressId = null;
		$this->billingDetails = null;
		$this->billingPeriod = null;
		$this->businessId = null;
		$this->currencyCode = null;
		$this->customData = null;
		$this->customerId = null;
		$this->items = null;
	}
}
