<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class InvoiceItem
{
    /**
     * The price of the product in the item
     * 
     * 
     * 
     * @var ?\paddle\Paddle\Models\Shared\InvoiceItemPrice $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\InvoiceItemPrice')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?InvoiceItemPrice $price = null;
    
    /**
     * Quantity of the product in the item, greater than 0
     * 
     * @var int $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $quantity;
    
	public function __construct()
	{
		$this->price = null;
		$this->quantity = 0;
	}
}
