<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * Meta - Information about this response.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class Meta
{
    /**
     * Unique ID for the request relating to this response. Provide this when contacting Paddle support about a specific request.
     * 
     * @var string $requestId
     */
	#[\JMS\Serializer\Annotation\SerializedName('request_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $requestId;
    
	public function __construct()
	{
		$this->requestId = "";
	}
}
