<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/** Type of payment method used for this payment attempt. */
enum MethodDetailsType: string
{
    case Card = 'card';
    case Paypal = 'paypal';
    case ApplePay = 'apple_pay';
    case WireTransfer = 'wire_transfer';
    case Alipay = 'alipay';
    case Ideal = 'ideal';
    case GooglePay = 'google_pay';
    case Offline = 'offline';
    case Unknown = 'unknown';
}
