<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * MethodDetails - Information about the payment method used for a payment attempt.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class MethodDetails
{
    /**
     * Information about the credit or debit card used to pay. Only returned when `type` is `card`.
     * 
     * @var ?\paddle\Paddle\Models\Shared\MethodDetailsCard $card
     */
	#[\JMS\Serializer\Annotation\SerializedName('card')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\MethodDetailsCard')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MethodDetailsCard $card = null;
    
    /**
     * Type of payment method used for this payment attempt.
     * 
     * @var ?\paddle\Paddle\Models\Shared\MethodDetailsType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\MethodDetailsType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?MethodDetailsType $type = null;
    
	public function __construct()
	{
		$this->card = null;
		$this->type = null;
	}
}
