<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class Money2
{
    /**
     * Amount in the lowest denomination for the currency, e.g. 10 USD = 1000 (cents).
     * 
     * @var string $amount
     */
	#[\JMS\Serializer\Annotation\SerializedName('amount')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $amount;
    
    /**
     * Supported three-letter ISO 4217 currency code.
     * 
     * @var \paddle\Paddle\Models\Shared\CurrencyCode2 $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCode2>')]
    public CurrencyCode2 $currencyCode;
    
	public function __construct()
	{
		$this->amount = "";
		$this->currencyCode = \paddle\Paddle\Models\Shared\CurrencyCode2::Ars;
	}
}
