<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/** Where notifications should be sent for this destination. */
enum NotificationSettingCreateType: string
{
    case Email = 'email';
    case Url = 'url';
}
