<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class Period2
{
    /**
     * Amount of time.
     * 
     * @var int $frequency
     */
	#[\JMS\Serializer\Annotation\SerializedName('frequency')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $frequency;
    
    /**
     * Unit of time.
     * 
     * @var \paddle\Paddle\Models\Shared\Period2Interval $interval
     */
	#[\JMS\Serializer\Annotation\SerializedName('interval')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\Period2Interval>')]
    public Period2Interval $interval;
    
	public function __construct()
	{
		$this->frequency = 0;
		$this->interval = \paddle\Paddle\Models\Shared\Period2Interval::Day;
	}
}
