<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/** How this adjustment impacts the related transaction. `refund` adjustments must be approved by Paddle, and are created with the status `pending_approval`. `chargeback` and `chargeback_warning` adjustments are created automatically by Paddle. */
enum Schemasaction: string
{
    case Credit = 'credit';
    case Refund = 'refund';
    case Chargeback = 'chargeback';
    case ChargebackWarning = 'chargeback_warning';
}
