<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/** Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses are set automatically by Paddle. */
enum SchemaStatusTransaction: string
{
    case Draft = 'draft';
    case Ready = 'ready';
    case Billed = 'billed';
    case Completed = 'completed';
    case Canceled = 'canceled';
    case PastDue = 'past_due';
}
