<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


enum StatusInvoice: string
{
    case Paid = 'paid';
    case Overdue = 'overdue';
    case PendingAcceptance = 'pending_acceptance';
    case Unpaid = 'unpaid';
    case Canceled = 'canceled';
    case Draft = 'draft';
}
