<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class SubscriptionChargeItems
{
    /**
     * Unique Paddle ID for this price, prefixed with `pri_`.
     * 
     * @var string $priceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('price_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $priceId;
    
    /**
     * Quantity to charge for.
     * 
     * @var float $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('float')]
    public float $quantity;
    
	public function __construct()
	{
		$this->priceId = "";
		$this->quantity = 0;
	}
}
