<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * SubscriptionNextTransaction - Preview of the next transaction for this subscription. May include prorated charges that are not yet billed and one-time charges. `null` if the subscription is scheduled to cancel or pause.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class SubscriptionNextTransaction
{
    /**
     * $adjustments
     * 
     * @var ?array<mixed> $adjustments
     */
	#[\JMS\Serializer\Annotation\SerializedName('adjustments')]
    #[\JMS\Serializer\Annotation\Type('array<mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $adjustments = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('billing_period')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TimePeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TimePeriod $billingPeriod = null;
    
    /**
     * Calculated totals for a transaction preview, including discounts, tax, and currency conversion. Considered the source of truth for totals on a transaction preview.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TransactionPreviewDetails $details
     */
	#[\JMS\Serializer\Annotation\SerializedName('details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TransactionPreviewDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionPreviewDetails $details = null;
    
	public function __construct()
	{
		$this->adjustments = null;
		$this->billingPeriod = null;
		$this->details = null;
	}
}
