<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * SubscriptionIncludesDiscount - Details of the discount applied to this subscription.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class SubscriptionIncludesDiscount
{
    /**
     * RFC 3339 datetime string.
     * 
     * @var \DateTime $endsAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('ends_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $endsAt;
    
    /**
     * Unique Paddle ID for this discount, prefixed with `dsc_`.
     * 
     * @var string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $id;
    
    /**
     * RFC 3339 datetime string.
     * 
     * @var \DateTime $startsAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('starts_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startsAt;
    
	public function __construct()
	{
		$this->endsAt = new \DateTime();
		$this->id = "";
		$this->startsAt = new \DateTime();
	}
}
