<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionBillingPeriod - The period of time that this transaction covers. This is used by recurring subscription transactions as well as all invoicing transactions to indicate the period of time the charges in the transaction relate to
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionBillingPeriod
{
    /**
     * End of the billing period. A timestamp following the RFC 3339 standard
     * 
     * @var \DateTime $endsAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('ends_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $endsAt;
    
    /**
     * Start of the billing period. A timestamp following the RFC 3339 standard. Cannot be a future date.
     * 
     * @var \DateTime $startsAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('starts_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    public \DateTime $startsAt;
    
	public function __construct()
	{
		$this->endsAt = new \DateTime();
		$this->startsAt = new \DateTime();
	}
}
