<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


class TransactionItemInput
{
    /**
     * Represents a price entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\PriceInput $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\PriceInput')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?PriceInput $price = null;
    
    /**
     * Unique Paddle ID for this price, prefixed with `pri_`.
     * 
     * @var string $priceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('price_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $priceId;
    
    /**
     * Quantity of this item on the transaction.
     * 
     * @var int $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $quantity;
    
	public function __construct()
	{
		$this->price = null;
		$this->priceId = "";
		$this->quantity = 0;
	}
}
