<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionPricingPreviewLineItemDiscount - Array of discounts applied to this preview line item. Empty if no discounts applied.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionPricingPreviewLineItemDiscount
{
    /**
     * Represents a discount entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Discount $discount
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Discount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Discount $discount = null;
    
    /**
     * Total amount discounted as a result of this discount in the format of a given currency. '
     * 
     * @var ?string $formattedTotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('formatted_total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $formattedTotal = null;
    
    /**
     * Total amount discounted as a result of this discount.
     * 
     * @var ?string $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $total = null;
    
	public function __construct()
	{
		$this->discount = null;
		$this->formattedTotal = null;
		$this->total = null;
	}
}
