<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionItemProration - How proration was calculated for this item. Populated when a transaction is created from a subscription change, where `proration_billing_mode` was `prorated_immediately` or `prorated_next_billing_period`. Set automatically by Paddle.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionItemProration
{
	#[\JMS\Serializer\Annotation\SerializedName('billing_period')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TimePeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TimePeriod $billingPeriod = null;
    
    /**
     * Rate used to calculate proration.
     * 
     * @var ?string $rate
     */
	#[\JMS\Serializer\Annotation\SerializedName('rate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $rate = null;
    
	public function __construct()
	{
		$this->billingPeriod = null;
		$this->rate = null;
	}
}
