<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionPricingPreviewLineItem - Information about line items for this preview. Includes totals calculated by Paddle. Considered the source of truth for line item totals.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionPricingPreviewLineItem
{
    /**
     * Array of discounts applied to this preview line item. Empty if no discounts applied.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TransactionPricingPreviewLineItemDiscount $discounts
     */
	#[\JMS\Serializer\Annotation\SerializedName('discounts')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TransactionPricingPreviewLineItemDiscount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionPricingPreviewLineItemDiscount $discounts = null;
    
    /**
     * The financial breakdown of a charge in the format of a given currency.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TotalsFormatted $formattedTotals
     */
	#[\JMS\Serializer\Annotation\SerializedName('formatted_totals')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TotalsFormatted')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TotalsFormatted $formattedTotals = null;
    
    /**
     * Breakdown of the charge for one unit in the format of a given currency.
     * 
     * @var ?\paddle\Paddle\Models\Shared\UnitTotalsFormatted $formattedUnitTotals
     */
	#[\JMS\Serializer\Annotation\SerializedName('formatted_unit_totals')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\UnitTotalsFormatted')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UnitTotalsFormatted $formattedUnitTotals = null;
    
    /**
     * Represents a price entity.
     * 
     * @var ?array<string, mixed> $price
     */
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $price = null;
    
    /**
     * Represents a product entity.
     * 
     * @var ?array<string, mixed> $product
     */
	#[\JMS\Serializer\Annotation\SerializedName('product')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $product = null;
    
    /**
     * Quantity of this preview line item.
     * 
     * @var ?float $quantity
     */
	#[\JMS\Serializer\Annotation\SerializedName('quantity')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $quantity = null;
    
    /**
     * Rate used to calculate tax for this preview line item.
     * 
     * @var ?string $taxRate
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax_rate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $taxRate = null;
    
    /**
     * The financial breakdown of a charge in the lowest denomination of a currency (eg cents for USD).
     * 
     * @var ?\paddle\Paddle\Models\Shared\Totals2 $totals
     */
	#[\JMS\Serializer\Annotation\SerializedName('totals')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Totals2')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Totals2 $totals = null;
    
    /**
     * Breakdown of the charge for one unit in the lowest denomination of a currency (e.g. cents for USD).
     * 
     * @var ?\paddle\Paddle\Models\Shared\UnitTotals $unitTotals
     */
	#[\JMS\Serializer\Annotation\SerializedName('unit_totals')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\UnitTotals')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UnitTotals $unitTotals = null;
    
	public function __construct()
	{
		$this->discounts = null;
		$this->formattedTotals = null;
		$this->formattedUnitTotals = null;
		$this->price = null;
		$this->product = null;
		$this->quantity = null;
		$this->taxRate = null;
		$this->totals = null;
		$this->unitTotals = null;
	}
}
