<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionIncludes - Represents a transaction entity.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionIncludes
{
    /**
     * Represents an address entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Address $address
     */
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Address')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Address $address = null;
    
    /**
     * Unique Paddle ID for this address entity, prefixed with `add_`.
     * 
     * @var ?string $addressId
     */
	#[\JMS\Serializer\Annotation\SerializedName('address_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $addressId = null;
    
    /**
     * List of adjustments for this transaction. Returned when the `include` parameter is used.
     * 
     * @var ?array<\paddle\Paddle\Models\Shared\Adjustment2> $adjustments
     */
	#[\JMS\Serializer\Annotation\SerializedName('adjustments')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\Adjustment2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $adjustments = null;
    
    /**
     * Breakdown of all the adjustments made against a transaction in the transaction currency.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TransactionAdjustmentsTotalsInclude $adjustmentsTotals
     */
	#[\JMS\Serializer\Annotation\SerializedName('adjustments_totals')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TransactionAdjustmentsTotalsInclude')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionAdjustmentsTotalsInclude $adjustmentsTotals = null;
    
    /**
     * RFC 3339 datetime string.
     * 
     * @var ?\DateTime $billedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('billed_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $billedAt = null;
    
    /**
     * Details for invoicing. Required if `collection_mode` is `manual`.
     * 
     * @var ?\paddle\Paddle\Models\Shared\BillingDetails2 $billingDetails
     */
	#[\JMS\Serializer\Annotation\SerializedName('billing_details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\BillingDetails2')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BillingDetails2 $billingDetails = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('billing_period')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TimePeriod')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TimePeriod $billingPeriod = null;
    
    /**
     * Represents a business entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Business $business
     */
	#[\JMS\Serializer\Annotation\SerializedName('business')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Business')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Business $business = null;
    
    /**
     * Unique Paddle ID for this business entity, prefixed with `biz_`.
     * 
     * @var ?string $businessId
     */
	#[\JMS\Serializer\Annotation\SerializedName('business_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $businessId = null;
    
    /**
     * Paddle Checkout details for this transaction. Always included for automatically-collected transactions. Included where `billing_details.enable_checkout` is `true` for manually-collected transactions.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TransactionIncludesCheckout $checkout
     */
	#[\JMS\Serializer\Annotation\SerializedName('checkout')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TransactionIncludesCheckout')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionIncludesCheckout $checkout = null;
    
    /**
     * How payment is collected. `automatic` for checkout, `manual` for invoices.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CollectionMode2 $collectionMode
     */
	#[\JMS\Serializer\Annotation\SerializedName('collection_mode')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CollectionMode2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CollectionMode2 $collectionMode = null;
    
    /**
     * RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.
     * 
     * @var ?\DateTime $createdAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $createdAt = null;
    
    /**
     * Supported three-letter ISO 4217 currency code.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CurrencyCode2 $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCode2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CurrencyCode2 $currencyCode = null;
    
    /**
     * Your own structured key-value data.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CustomData $customData
     */
	#[\JMS\Serializer\Annotation\SerializedName('custom_data')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\CustomData')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CustomData $customData = null;
    
    /**
     * Represents a customer entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Customer $customer
     */
	#[\JMS\Serializer\Annotation\SerializedName('customer')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Customer')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Customer $customer = null;
    
    /**
     * Unique Paddle ID for this customer entity, prefixed with `ctm_`.
     * 
     * @var ?string $customerId
     */
	#[\JMS\Serializer\Annotation\SerializedName('customer_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $customerId = null;
    
    /**
     * Calculated totals for a transaction, including proration, discounts, tax, and currency conversion. Considered the source of truth for totals on a transaction.
     * 
     * @var ?\paddle\Paddle\Models\Shared\TransactionDetails $details
     */
	#[\JMS\Serializer\Annotation\SerializedName('details')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\TransactionDetails')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?TransactionDetails $details = null;
    
    /**
     * Represents a discount entity.
     * 
     * @var ?\paddle\Paddle\Models\Shared\Discount $discount
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount')]
    #[\JMS\Serializer\Annotation\Type('paddle\Paddle\Models\Shared\Discount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Discount $discount = null;
    
    /**
     * Unique Paddle ID for this discount, prefixed with `dsc_`.
     * 
     * @var ?string $discountId
     */
	#[\JMS\Serializer\Annotation\SerializedName('discount_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $discountId = null;
    
    /**
     * Unique Paddle ID for this transaction entity, prefixed with `txn_`.
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * Paddle ID of the invoice that this transaction is related to, prefixed with `inv_`. Used for compatibility with the initial version of the Paddle Invoice API.
     * 
     * @var ?string $invoiceId
     */
	#[\JMS\Serializer\Annotation\SerializedName('invoice_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $invoiceId = null;
    
    /**
     * Invoice number for this transaction. Automatically generated by Paddle when you mark a transaction as `billed` where `collection_mode` is `manual`.
     * 
     * @var ?string $invoiceNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('invoice_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $invoiceNumber = null;
    
    /**
     * List of items on this transaction. For calculated totals, use `details.line_items`.
     * 
     * @var ?array<\paddle\Paddle\Models\Shared\TransactionItem> $items
     */
	#[\JMS\Serializer\Annotation\SerializedName('items')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\TransactionItem>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $items = null;
    
    /**
     * Describes how this transaction was created.
     * 
     * @var ?\paddle\Paddle\Models\Shared\OriginTransaction $origin
     */
	#[\JMS\Serializer\Annotation\SerializedName('origin')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\OriginTransaction>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?OriginTransaction $origin = null;
    
    /**
     * List of payment attempts for this transaction, including successful payments. Sorted by `created_at` in descending order, so most recent attemps are returned first.
     * 
     * @var ?array<\paddle\Paddle\Models\Shared\TransactionPaymentAttempt> $payments
     */
	#[\JMS\Serializer\Annotation\SerializedName('payments')]
    #[\JMS\Serializer\Annotation\Type('array<paddle\Paddle\Models\Shared\TransactionPaymentAttempt>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $payments = null;
    
    /**
     * Status of this transaction. You may set a transaction to `billed` or `canceled`, other statuses are set automatically by Paddle.
     * 
     * @var ?\paddle\Paddle\Models\Shared\SchemasstatusTransaction $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\SchemasstatusTransaction>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SchemasstatusTransaction $status = null;
    
    /**
     * Unique Paddle ID for this subscription entity, prefixed with `sub_`.
     * 
     * @var ?string $subscriptionId
     */
	#[\JMS\Serializer\Annotation\SerializedName('subscription_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subscriptionId = null;
    
    /**
     * RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
     * 
     * @var ?\DateTime $updatedAt
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $updatedAt = null;
    
	public function __construct()
	{
		$this->address = null;
		$this->addressId = null;
		$this->adjustments = null;
		$this->adjustmentsTotals = null;
		$this->billedAt = null;
		$this->billingDetails = null;
		$this->billingPeriod = null;
		$this->business = null;
		$this->businessId = null;
		$this->checkout = null;
		$this->collectionMode = null;
		$this->createdAt = null;
		$this->currencyCode = null;
		$this->customData = null;
		$this->customer = null;
		$this->customerId = null;
		$this->details = null;
		$this->discount = null;
		$this->discountId = null;
		$this->id = null;
		$this->invoiceId = null;
		$this->invoiceNumber = null;
		$this->items = null;
		$this->origin = null;
		$this->payments = null;
		$this->status = null;
		$this->subscriptionId = null;
		$this->updatedAt = null;
	}
}
