<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace paddle\Paddle\Models\Shared;


/**
 * TransactionTotalsAdjusted - Breakdown of the payout totals for a transaction after adjustments. `null` until the transaction is `completed`.
 * 
 * @package paddle\Paddle\Models\Shared
 * @access public
 */
class TransactionTotalsAdjusted
{
    /**
     * Supported three-letter ISO 4217 currency code.
     * 
     * @var ?\paddle\Paddle\Models\Shared\CurrencyCode2 $currencyCode
     */
	#[\JMS\Serializer\Annotation\SerializedName('currency_code')]
    #[\JMS\Serializer\Annotation\Type('enum<paddle\Paddle\Models\Shared\CurrencyCode2>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CurrencyCode2 $currencyCode = null;
    
    /**
     * Total earnings for this transaction. This is the total minus the Paddle fee. 
     * 
     * `null` until the transaction is `completed` and the fee is processed.
     * 
     * @var ?string $earnings
     */
	#[\JMS\Serializer\Annotation\SerializedName('earnings')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $earnings = null;
    
    /**
     * Total fee taken by Paddle for this transaction. `null` until the transaction is `completed` and the fee is processed.
     * 
     * @var ?string $fee
     */
	#[\JMS\Serializer\Annotation\SerializedName('fee')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $fee = null;
    
    /**
     * Total due after credits but before any payments.
     * 
     * @var ?string $grandTotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('grand_total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $grandTotal = null;
    
    /**
     * Subtotal before discount, tax, and deductions. If an item, unit price multiplied by quantity.
     * 
     * @var ?string $subtotal
     */
	#[\JMS\Serializer\Annotation\SerializedName('subtotal')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subtotal = null;
    
    /**
     * Total tax on the subtotal.
     * 
     * @var ?string $tax
     */
	#[\JMS\Serializer\Annotation\SerializedName('tax')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tax = null;
    
    /**
     * Total after tax.
     * 
     * @var ?string $total
     */
	#[\JMS\Serializer\Annotation\SerializedName('total')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $total = null;
    
	public function __construct()
	{
		$this->currencyCode = null;
		$this->earnings = null;
		$this->fee = null;
		$this->grandTotal = null;
		$this->subtotal = null;
		$this->tax = null;
		$this->total = null;
	}
}
